#!/usr/bin/env python
__author__ = 'leahanderson'
import xml.etree.ElementTree as ET
import csv


#input file is a csv of a matrix with inputs being the rows and outputs corresponding to columns (so row sums=1)
with open('splits_v5.csv') as csvfile:
    matreader = csv.reader(csvfile, delimiter=',')
    output_links = matreader.next()
    output_links.pop(0)
    input_links={}
    for row in matreader:
        counter=1
        input_links[row[0]]={}
        for col in output_links:
            if row[counter]>0:
                input_links[row[0]][col] = row[counter]
            counter+=1



#also need a corresponding network xml as generated by scenario editor...
tree = ET.parse('Lshim_v5_SignalController_demand.xml')
scenario = tree.getroot()
networkxml=scenario.find('NetworkSet').find('network')
link_set = networkxml.find('LinkList')
node_splits={}
for l in link_set:
    link_id = l.attrib['id']
    if link_id in input_links.keys():
        node_id = l.find('end').attrib['node_id']
        if node_id not in node_splits.keys():
            node_splits[node_id]=[]
        for out_link, split_ratio in input_links[link_id].iteritems():
            if float(split_ratio) > 0:
                node_splits[node_id].append([link_id, out_link, split_ratio])
# print node_splits
split_set = ET.SubElement(scenario, 'SplitRatioSet')
for n, ns in node_splits.iteritems():
    split_item = ET.SubElement(split_set, 'splitRatioProfile')
    split_item.attrib={'id':n, 'node_id':n, 'start_time':'0', 'dt':'1'}
    for s in ns:
        print s
        split_ratio = ET.SubElement(split_item, 'splitratio')
        split_ratio.attrib={'link_in':s[0], 'link_out':s[1], 'vehicle_type_id':'1'}
        split_ratio.text=s[2]

tree.write("Lshim_v5_SignalController_demand_splits.xml")





